server:
  port: 9000

---

spring:
  profiles: default

redis:
  hostname: localhost

io:
  block16:
    nodeLocation: http://localhost:8545

amqp:
  host: localhost

---

spring:
  profiles: compose

redis:
  hostname: redis

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

---

spring:
  profiles: prod

redis:
  hostname: redis.block16.io

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

amqp:
  host: rabbit.block16.io