
---

spring:
  profiles: default

redis:
  hostname: localhost

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO


---

spring:
  profiles: compose

redis:
  hostname: redis

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

---

spring:
  profiles: prod

redis:
  hostname: redis.internal.block16

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO